name: Test and Release

on:
  push:
    branches:
      - '**'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Upgrade pip and Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Python dependencies with binary preference
        run: |
          pip install pytest pytest-workflow miniwdl

      - name: Run tests with Docker
        run: |
          pytest tasks/

  release:
    needs: [test]
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create tar.gz of directories
        run: tar -czvf release.tar.gz pipelines tasks

      - name: Create a Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            release.tar.gz
